name: CI
on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: wasilibs/actions/.github/workflows/ci.yaml@435fbabb9723e77fd6ba71e6ec8744efd1a56be1
    secrets: inherit

  example:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5
        with:
          go-version-file: go.work
          cache-dependency-path: "**/go.sum"

      - name: build example
        run: go run github.com/bufbuild/buf/cmd/buf@v1.32.0 generate
        working-directory: example
